services:
  postgres:
    image: postgres:16
    container_name: petconnect-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: petconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: petconnect
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: