version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4  # Uses the official PostGIS image
    container_name: petconnect-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: petconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: petconnect
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
