CREATE TABLE pet
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(50),
    species              VARCHAR(50),
    available            BOOLEAN                                 NOT NULL,
    age                  INTEGER                                 NOT NULL,
    owner                VARCHAR(255),
    location             VARCHAR(255),
    profile_picture_path VARCHAR(255),
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE user_table
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             VARCHAR(50),
    email                VARCHAR(255),
    password             VARCHAR(255),
    profile_picture_path VARCHAR(255),
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);